Api
escalopa/task-tracker-frontend pull request #3
Opened 2022-03-24 22:13 UTC by escalopa

2022-03-24 22:24 UTC, escalopa commented
When sending the sign up request i get this error, anyideas what is causing it ???
I have checked already the naming of the my variables and they match the query parameters ones 

![Screenshot from 2022-03-25 01-01-55](https://user-images.githubusercontent.com/58439278/160020077-2ab70e83-3034-493e-b07d-26543570d154.png)

2022-03-24 22:26 UTC, escalopa commented
1 more thing, I have added CI/CD but the chnages were in the main branch but you can find it in the git/workflow in my repo, if there anything that needs editing please let me know

2022-04-03 12:02 UTC, DmitriyFirsov requested changes

2022-04-03 12:02 UTC, DmitriyFirsov commented on .env
> +REACT_APP_API_URL=https://itis-task-tracker-be.herokuapp.com
Этот файл должен быть в игноре
Это нужно для удобного управления переменными окружения

2022-04-03 12:02 UTC, DmitriyFirsov commented on package.json
>      "@testing-library/jest-dom": "^5.14.1",
все пакеты `@testing-library` нужно в devDependencies перенести

2022-04-03 12:02 UTC, DmitriyFirsov commented on src/components/EnvSpecificRouter.js
> +export default function EnvSpecificRouter({children}) {
Понятно для чего это было сделано?

2022-04-03 12:02 UTC, DmitriyFirsov commented on src/pages/login.js
>    const togglePasswordVisiblity = () => {
Опечатка - `togglePasswordVisibility`

2022-04-03 12:02 UTC, DmitriyFirsov commented on src/pages/login.js
>  import {LoginFormValidator} from '../validators/login_form_validator'
Только рект компоненты должны называться с большой буквы

2022-04-03 12:02 UTC, DmitriyFirsov commented on src/validators/form_validators/email_validator.js
>  export const EmailValidator = (email) => {
дожна называться с маленькой буквы

2022-04-03 12:02 UTC, DmitriyFirsov commented on src/pages/login.js
>    const [isSubmit, setIsSubmit] = useState(false)
бесполезное состояние - состояние отправки можно через isLoading  взять 
из [ строки 33 ](https://github.com/escalopa/task-tracker-frontend/pull/3/files?diff=split&w=1#diff-986ee2e4b2fbfde6bd81b45c75ea088031ac4e40f1761d0f898015eeb81c1777R33)

2022-04-03 12:02 UTC, DmitriyFirsov commented on src/pages/registration.js
> +  const [isSubmit, setIsSubmit] = useState(false)
бесполезное состояние

2022-04-03 12:02 UTC, DmitriyFirsov commented on src/utils/forms/errorChecker.js
> +export default function isErrorStateEmpty(obj) {
название файла не соотвествует названию функции

2022-04-03 12:04 UTC, DmitriyFirsov commented
в js проектах принят camalCase формат для файлов и переменных
рект компоненты должны начинаться с большой буквы

2022-04-03 12:04 UTC, DmitriyFirsov commented
yarn.lock файл не нужен, тк как я понял ты пользушься npm

2022-04-04 14:32 UTC, escalopa commented on src/components/EnvSpecificRouter.js
> +export default function EnvSpecificRouter({children}) {
To use a specific router(if exists in .env file), otherwise use the default browser router.

2022-04-04 14:41 UTC, escalopa commented on src/pages/login.js
>    const [isSubmit, setIsSubmit] = useState(false)
всм взять от isLoading ??
isLoading это boolean и у меня SmallError, handleFormCHange нужны
насколько я тебя понял, ты предлагаешь их убирать да ?

2022-04-04 14:42 UTC, escalopa commented on src/pages/registration.js
> +  const [isSubmit, setIsSubmit] = useState(false)
тут без них не могу проверять полей формы, как их убирать

2022-04-04 14:43 UTC, escalopa commented on src/pages/login.js
>  import {LoginFormValidator} from '../validators/login_form_validator'
переделаю все мои компоненты, потому что плохо у меня сдельно

2022-04-04 17:19 UTC, DmitriyFirsov approved these changes

2022-04-04 17:27 UTC, DmitriyFirsov approved these changes

2022-04-18 13:20 UTC, closed without merging